// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkDomainPermission } from "./NetworkDomainPermission";

export type NetworkRequirements = { enabled: boolean | null, httpPort: number | null, socksPort: number | null, allowUpstreamProxy: boolean | null, dangerouslyAllowNonLoopbackProxy: boolean | null,
/**
 * Canonical network permission map for `experimental_network`.
 */
domains: { [key in string]?: NetworkDomainPermission } | null,
/**
 * When true, only managed allowlist entries are respected while managed
 * network enforcement is active.
 */
managedAllowedDomainsOnly: boolean | null,
/**
 * Legacy compatibility view derived from `domains`.
 */
allowedDomains: Array<string> | null,
/**
 * Legacy compatibility view derived from `domains`.
 */
deniedDomains: Array<string> | null, allowLocalBinding: boolean | null, };
